# Generated by Django 2.1.7 on 2019-05-06 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20190506_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='speed',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='stamina',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='strength',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=10),
        ),
    ]
